[package]
name = "belajar-say-hello"
version = "0.3.0"
edition = "2021"
description = "This is say hello library"
license = "Apache-2.0"

[features]
hello = []
bye = []
all = ["hello", "bye"]
default = ["hello"]

[dependencies]
